FROM python:3.8

# Set working directory in the container
WORKDIR /app

# Install dependencies directly
RUN pip install --no-cache-dir prometheus_client==0.14.1 pymongo==4.2.0 redis==5.0.3 pandas==1.3.4 requests==2.31.0 tqdm==4.66.2 snowflake-connector-python==3.14.0

COPY . .

# Command to run the exporter
CMD ["python", "./monitor/custom_exporter_script.py"]
