global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'weatherflow-prometheus:9090'

  - job_name: node
    static_configs:
      - targets:
          - 'weatherflow-node-exporter:9100'
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['weatherflow-cadvisor:8081']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: custom_metrics_job
    static_configs:
      - targets:
          - 'weatherflow-custom-exporter:8000'